name: Build Next.js web application

on: pull_request

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm install
      
      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

      - name: Build project assets
        run: npm run build
